### ISSUE TITLE
Using `cloudinaryAssetData` via frontmatter

### ISSUE THREAD

**Issue by tpiros** [cloudinary-devs/gatsby-transformer-cloudinary#87]
This is more a question, than a bug report probably. I was wondering if it's possible to use frontmatter data as opposed to a json object to describe the `cloudinaryAssetData`?

I tried to following but it's not working:

*post.md*
```
---
date: "2021-02-21"
title: "titlel"
intro: "Details of the trip to nowhere"
author: "Linda Watkins"
coverPhoto:
  cloudinaryAssetData: true,
  cloudName: "<>"
  publicId: "pID"
---

blog entry ....
```
